"""Add other_roles to member

Revision ID: 2537118ca1d7
Revises: d24b2cfd67da
Create Date: 2026-04-24 09:12:10.745031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2537118ca1d7'
down_revision: Union[str, None] = 'd24b2cfd67da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('other_roles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'other_roles')
    # ### end Alembic commands ###
