"""Add calendar, settings, is_important

Revision ID: c65a39a553b3
Revises: f36da29ae76c
Create Date: 2026-04-28 08:46:47.019324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c65a39a553b3'
down_revision: Union[str, None] = 'f36da29ae76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idle_report_enabled', sa.Boolean(), nullable=False),
    sa.Column('idle_report_morning_time', sa.String(length=10), nullable=False),
    sa.Column('idle_report_evening_time', sa.String(length=10), nullable=False),
    sa.Column('late_report_enabled', sa.Boolean(), nullable=False),
    sa.Column('late_report_time', sa.String(length=10), nullable=False),
    sa.Column('chatops_pm_group_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('working_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_calendar_calendar_date'), 'working_calendar', ['calendar_date'], unique=False)
    op.create_index(op.f('ix_working_calendar_member_id'), 'working_calendar', ['member_id'], unique=False)
    op.create_index(op.f('ix_working_calendar_type'), 'working_calendar', ['type'], unique=False)
    op.add_column('project', sa.Column('is_important', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_project_is_important'), 'project', ['is_important'], unique=False)
    op.alter_column('task', 'description',
               existing_type=mysql.TEXT(collation='utf8_unicode_ci'),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(collation='utf8_unicode_ci'),
               existing_nullable=True)
    op.drop_index(op.f('ix_project_is_important'), table_name='project')
    op.drop_column('project', 'is_important')
    op.drop_index(op.f('ix_working_calendar_type'), table_name='working_calendar')
    op.drop_index(op.f('ix_working_calendar_member_id'), table_name='working_calendar')
    op.drop_index(op.f('ix_working_calendar_calendar_date'), table_name='working_calendar')
    op.drop_table('working_calendar')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
