"""Add User model and link Member to User

Revision ID: cd8b91707d96
Revises: 94d71de7b3e8
Create Date: 2026-04-24 13:26:12.381881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd8b91707d96'
down_revision: Union[str, None] = '94d71de7b3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('system_role', sa.Enum('ADMIN', 'PM', 'MEMBER', name='systemrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mattermost_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('member', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_user_id'), 'member', ['user_id'], unique=False)
    op.create_foreign_key(None, 'member', 'user', ['user_id'], ['id'])
    op.drop_column('member', 'system_role')
    op.drop_column('member', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('hashed_password', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False))
    op.add_column('member', sa.Column('system_role', mysql.ENUM('ADMIN', 'PM', 'MEMBER', collation='utf8_unicode_ci'), nullable=False))
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_index(op.f('ix_member_user_id'), table_name='member')
    op.drop_column('member', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
