"""Initial migration

Revision ID: d24b2cfd67da
Revises: 
Create Date: 2026-04-24 08:45:17.206777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24b2cfd67da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_department_is_deleted'), 'department', ['is_deleted'], unique=False)
    op.create_table('member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('system_role', sa.Enum('ADMIN', 'PM', 'MEMBER', name='memberrole'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('default_role', sa.String(length=80), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_member_department_id'), 'member', ['department_id'], unique=False)
    op.create_index(op.f('ix_member_is_deleted'), 'member', ['is_deleted'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_department_id'), 'project', ['department_id'], unique=False)
    op.create_index(op.f('ix_project_is_deleted'), 'project', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_project_pm_id'), 'project', ['pm_id'], unique=False)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('is_hidden', sa.Integer(), nullable=False),
    sa.Column('hidden_reason', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'member_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_member_is_hidden'), 'project_member', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_project_member_member_id'), 'project_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_project_member_project_id'), 'project_member', ['project_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_department_id'), 'task', ['department_id'], unique=False)
    op.create_index(op.f('ix_task_is_deleted'), 'task', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_task_pm_id'), 'task', ['pm_id'], unique=False)
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_table('task_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('is_hidden', sa.Integer(), nullable=False),
    sa.Column('hidden_reason', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'member_id', name='uq_task_member')
    )
    op.create_index(op.f('ix_task_member_is_hidden'), 'task_member', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_task_member_member_id'), 'task_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_task_member_task_id'), 'task_member', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_member_task_id'), table_name='task_member')
    op.drop_index(op.f('ix_task_member_member_id'), table_name='task_member')
    op.drop_index(op.f('ix_task_member_is_hidden'), table_name='task_member')
    op.drop_table('task_member')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_index(op.f('ix_task_pm_id'), table_name='task')
    op.drop_index(op.f('ix_task_is_deleted'), table_name='task')
    op.drop_index(op.f('ix_task_department_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_project_member_project_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_member_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_is_hidden'), table_name='project_member')
    op.drop_table('project_member')
    op.drop_index(op.f('ix_project_status'), table_name='project')
    op.drop_index(op.f('ix_project_pm_id'), table_name='project')
    op.drop_index(op.f('ix_project_is_deleted'), table_name='project')
    op.drop_index(op.f('ix_project_department_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_member_is_deleted'), table_name='member')
    op.drop_index(op.f('ix_member_department_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_department_is_deleted'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
