"""Add description to ProjectMember

Revision ID: f36da29ae76c
Revises: cd8b91707d96
Create Date: 2026-04-24 13:33:10.557030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36da29ae76c'
down_revision: Union[str, None] = 'cd8b91707d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_member', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_member', 'description')
    # ### end Alembic commands ###
